<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>smallrye-health-parent</artifactId>
    <groupId>io.smallrye</groupId>
    <version>3.2.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>mp-5</artifactId>
  <name>SmallRye Health: MicroProfile 5</name>
  <packaging>pom</packaging>

  <modules>
    <module>transformations</module>
      <module>tck</module>
    </modules>

  <properties>
    <!-- Copied from https://github.com/smallrye/smallrye-parent/blob/31/full-parent-jakarta/pom.xml to override
    version in smallrye-parent with versions from smallrye-jakarta-parent to which we will switch once we move the
    whole project to jakarta dependencies. This is a workaround to get the whole project compile with one command. -->
    <!-- Dependency versions -->
    <version.jakarta.api>9.1.0</version.jakarta.api>
    <version.jakarta.annotation.api>2.0.0</version.jakarta.annotation.api>
    <version.jakarta.enterprise.cdi.api>3.0.0</version.jakarta.enterprise.cdi.api>
    <version.jakarta.json-p.api>2.0.1</version.jakarta.json-p.api>
    <version.jakarta.json-b.api>2.0.0</version.jakarta.json-b.api>
    <version.jakarta.ws.rs.api>3.0.0</version.jakarta.ws.rs.api>
    <version.jakarta.jms.api>3.0.0</version.jakarta.jms.api>

    <version.org.jboss.logging>3.4.2.Final</version.org.jboss.logging>
    <version.org.jboss.logging-processor>2.2.1.Final</version.org.jboss.logging-processor>
    <version.weld.api>4.0.Final</version.weld.api>
    <version.weld.core>4.0.1.SP1</version.weld.core>
    <version.org.jboss.jandex>2.4.0.Final</version.org.jboss.jandex>
    <version.glassfish.json>2.0.1</version.glassfish.json>

    <!-- Testing versions -->
    <version.assertj>3.19.0</version.assertj>
    <version.awaitility>4.1.0</version.awaitility>
    <version.org.jboss.arquillian>1.7.0.Alpha10</version.org.jboss.arquillian>
    <version.org.jboss.arquillian.container.weld-embedded>3.0.0.Final</version.org.jboss.arquillian.container.weld-embedded>
    <version.org.jboss.arquillian.wildfly>4.0.0.Alpha1</version.org.jboss.arquillian.wildfly>
    <version.junit>4.13.2</version.junit>
    <version.junit5>5.7.2</version.junit5>
    <version.weld.junit>3.0.0.Final</version.weld.junit>
    <version.rest-assured>4.4.0</version.rest-assured>
    <version.testng>7.4.0</version.testng>
    <version.testcontainers>1.15.3</version.testcontainers>

    <!-- MP 5 version of MP Health -->
    <version.eclipse.microprofile.health>4.0-RC2</version.eclipse.microprofile.health>
  </properties>
</project>
