<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>transformations</artifactId>
    <groupId>io.smallrye</groupId>
    <version>3.2.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>smallrye-health-api-transformed</artifactId>
  <name>SmallRye Health: API - Transformed</name>

  <properties>
    <transformer-input-dir>${project.basedir}/../../../api</transformer-input-dir>
    <version.org.wildfly.extras.batavia>1.0.10.Final</version.org.wildfly.extras.batavia>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.microprofile.health</groupId>
      <artifactId>microprofile-health-api</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.enterprise</groupId>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.common</groupId>
      <artifactId>smallrye-common-annotation</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>mutiny</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>
